"""Distill 原型 — Day 5 尹一帆。

从 ``.quantcode/rlhf_data.jsonl`` 读取历史 tool 调用,识别重复操作模式,
生成候选 ``SKILL.md`` 草案到 ``.quantcode/distill/drafts/``。

算法(纯 stdlib,无 LLM 依赖):
1. 读 RLHF JSONL,提取每条 ``action.tool_name + action.tool_args`` 签名
2. 按签名分组,统计出现次数
3. 出现次数 ``>= threshold`` 的签名视为"重复 pattern"
4. 对每个重复 pattern 生成 SKILL.md 草案(模板 4 段: 触发条件 / 步骤 / 验证 / 备注)

设计要点:
- 不调 LLM —— 维护难度低 + 0 外部依赖,符合方案对比选择
- 草案文件名格式: ``draft-{tool_name}-{hash}.md``,hash 来自 args 序列化
- 输出目录不存在自动创建
- RLHF 文件不存在或为空 → 返 [],不抛异常
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _action_signature(action: dict) -> tuple[str, str]:
    """从 RLHF action 字段提取 (tool_name, args_hash) 签名。

    args 用 ``json.dumps(sort_keys=True, default=str)`` 序列化后取 sha256 前 8 位。
    """
    tool_name = action.get("tool_name", "unknown")
    tool_args = action.get("tool_args", {})
    args_str = json.dumps(tool_args, sort_keys=True, default=str, ensure_ascii=False)
    args_hash = hashlib.sha256(args_str.encode("utf-8")).hexdigest()[:8]
    return tool_name, args_hash


def _read_rlhf(rlhf_path: Path) -> list[dict]:
    """读 RLHF JSONL 文件,跳过空行/坏行。文件不存在返 []。"""
    if not rlhf_path.exists():
        return []
    records: list[dict] = []
    with rlhf_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return records


def _generate_draft(
    tool_name: str,
    args_hash: str,
    sample_args: dict,
    count: int,
    threads: list[str],
) -> str:
    """生成一份 SKILL.md 草案内容。"""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    args_summary = json.dumps(sample_args, ensure_ascii=False, default=str, indent=2)
    threads_preview = ", ".join(threads[:5])
    if len(threads) > 5:
        threads_preview += f"... (+{len(threads) - 5} more)"
    body = f"""# {tool_name} ({args_hash}) — Distill Draft

> **Status**: Day 5 Distill prototype — needs human review before adopting as SKILL.
> **Generated**: {today}
> **Frequency**: {count} occurrences across {len(threads)} thread(s)

## Trigger / 触发条件

When the Agent decides to call `{tool_name}` with args matching:

```json
{args_summary}
```

## Steps / 步骤

1. (待人工填写) Step 1: ...
2. (待人工填写) Step 2: ...
3. (待人工填写) Step 3: ...

## Verify / 验证

(待人工填写) How to verify this skill succeeded. e.g. assert output schema, check side effects.

## Notes / 备注

- Source threads: {threads_preview}
- This draft was auto-generated by Distill (tool_call frequency analysis).
- Adopt by: review → fill in Steps / Verify → move to `.opencode/groups/<group>/skills/<name>/SKILL.md`.
"""
    return body


def distill(
    rlhf_path: str | Path,
    output_dir: str | Path,
    *,
    threshold: int = 3,
) -> list[Path]:
    """Distill 主入口:读 RLHF → 识别重复 pattern → 生成 SKILL.md 草案。

    Args:
        rlhf_path: RLHF 数据文件路径(JSONL)
        output_dir: 草案输出目录(不存在自动创建)
        threshold: 视为重复模式的最小次数

    Returns:
        生成的草案文件路径列表(按出现次数倒序)
    """
    rlhf_path = Path(rlhf_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    records = _read_rlhf(rlhf_path)
    if not records:
        return []

    # 按 (tool_name, args_hash) 分组
    groups: dict[tuple[str, str], dict[str, Any]] = {}
    for rec in records:
        action = rec.get("action", {})
        sig = _action_signature(action)
        if sig not in groups:
            groups[sig] = {
                "tool_name": sig[0],
                "args_hash": sig[1],
                "sample_args": action.get("tool_args", {}),
                "count": 0,
                "threads": [],
            }
        groups[sig]["count"] += 1
        tid = rec.get("thread_id", "unknown")
        if tid not in groups[sig]["threads"]:
            groups[sig]["threads"].append(tid)

    # 过滤 ≥ threshold + 按 count 倒序
    candidates = [info for info in groups.values() if info["count"] >= threshold]
    candidates.sort(key=lambda x: x["count"], reverse=True)

    generated: list[Path] = []
    for info in candidates:
        draft_body = _generate_draft(
            tool_name=info["tool_name"],
            args_hash=info["args_hash"],
            sample_args=info["sample_args"],
            count=info["count"],
            threads=info["threads"],
        )
        draft_filename = f"draft-{info['tool_name']}-{info['args_hash']}.md"
        draft_path = output_dir / draft_filename
        draft_path.write_text(draft_body, encoding="utf-8")
        generated.append(draft_path)

    return generated


__all__ = ["distill"]