"""QuantCode Pydantic schemas.

Pydantic v2 is the Source of Truth (per Design §5.5). JSON Schema is
generated from Pydantic via `model_json_schema()`; JSON files under this
directory are legacy JSON Schema artefacts kept for CI validation until
callers migrate to Pydantic.

Foundational schemas (Pattern 1 + Pattern 2 contracts):
- ComposeTask       — task envelope (Pattern 1: Orchestrator-Worker)
- BlackboardState   — shared state layer (Pattern 2: Stateful Blackboard)
- ComposeTaskEvent  — append-only audit trail
"""
from .compose_task import (
    BlackboardEntry,
    BlackboardScope,
    BlackboardState,
    ComposeTask,
    ComposeTaskEvent,
    GroupName,
    MAX_TREE_DEPTH,
    SESSION_ID_PATTERN,
    TASK_ID_PATTERN,
    TaskEventKind,
    TaskOutcome,
    TaskStatus,
    WritePolicy,
)
from .factor import (
    DateRange,
    DecayMetrics,
    FactorReport,
    FactorSpec,
    FactorVerdict,
    ICMetrics,
    ICMethod,
    LayeredBacktest,
    TurnoverMetrics,
)
from .fundamental import (
    CorpusType,
    PITDocument,
    PITQuery,
    PITResult,
    ResearchResult,
    ResearchSpec,
    SectionType,
    TargetType,
)
from .human_gate import (
    HumanGate,
    HumanGateDecision,
    HumanGateDecisionAction,
    HumanGateInterruptPayload,
    HumanGateStatus,
)
from .model import ModelRiskMetadata, ModelSpec, ModelType
from .options import (
    GreeksProfile,
    GreeksSnapshot,
    OptionSide,
    OptionsBacktestReport,
    OptionsDataSource,
    OptionsPosition,
    OptionsPositionLeg,
    OptionsSpec,
    OptionsStrategySpec,
    VolSurfacePoint,
    VolSurfaceResult,
)
from .risk_profile import RiskGateVerdict, RiskProfile, RiskThresholds
from .risk_gate_artifact import (
    AgenticRiskGateVerdict,
    BacktestAdapter,
    BacktestEvidence,
    BacktestRiskMetrics,
    BacktestWindow,
    BusinessRiskBinding,
    DataObjectEvidence,
    DataRequest,
    EvidenceStatus,
    ExecutionPolicy,
    HumanGateEvidenceBinding,
    PRBinding,
    RiskApplicability,
    RiskFinding,
    RiskGateArtifact,
    RiskGatePlan,
    RiskGatePlanDraft,
    RiskGatePlanProposal,
    RiskSubject,
    RiskSubjectKind,
)
from .risk_gate_task import (
    RiskGateCoverage,
    RiskGateEvidence,
    RiskGateExecutionRequest,
    RiskGateFailureAction,
    RiskGateProcessStep,
    RiskGateReason,
    RiskGateScope,
    RiskGateScopeTarget,
    RiskGateSubagentProvenance,
    RiskGateTaskArtifact,
    RiskGateTaskDraft,
    RiskGateTaskProposal,
    RiskGateTrigger,
    RiskGateTriggerDecision,
)
from .strategy import (
    BacktestSummary,
    SignalCandidate,
    StrategyReport,
    StrategySpec,
    StrategyVerdict,
)

__all__ = [
    "BlackboardEntry",
    "BlackboardScope",
    "BlackboardState",
    "ComposeTask",
    "ComposeTaskEvent",
    "GroupName",
    "MAX_TREE_DEPTH",
    "SESSION_ID_PATTERN",
    "TASK_ID_PATTERN",
    "TaskEventKind",
    "TaskOutcome",
    "TaskStatus",
    "WritePolicy",
    "ModelRiskMetadata",
    "ModelSpec",
    "ModelType",
    "DateRange",
    "DecayMetrics",
    "FactorReport",
    "FactorSpec",
    "FactorVerdict",
    "ICMetrics",
    "ICMethod",
    "LayeredBacktest",
    "TurnoverMetrics",
    "CorpusType",
    "PITDocument",
    "PITQuery",
    "PITResult",
    "ResearchResult",
    "ResearchSpec",
    "SectionType",
    "TargetType",
    "HumanGate",
    "HumanGateDecision",
    "HumanGateDecisionAction",
    "HumanGateInterruptPayload",
    "HumanGateStatus",
    "RiskGateVerdict",
    "RiskProfile",
    "RiskThresholds",
    "AgenticRiskGateVerdict",
    "BacktestAdapter",
    "BacktestEvidence",
    "BacktestRiskMetrics",
    "BacktestWindow",
    "BusinessRiskBinding",
    "DataObjectEvidence",
    "DataRequest",
    "EvidenceStatus",
    "ExecutionPolicy",
    "HumanGateEvidenceBinding",
    "PRBinding",
    "RiskApplicability",
    "RiskFinding",
    "RiskGateArtifact",
    "RiskGatePlan",
    "RiskGatePlanDraft",
    "RiskGatePlanProposal",
    "RiskSubject",
    "RiskSubjectKind",
    "RiskGateCoverage",
    "RiskGateEvidence",
    "RiskGateExecutionRequest",
    "RiskGateFailureAction",
    "RiskGateProcessStep",
    "RiskGateReason",
    "RiskGateScope",
    "RiskGateScopeTarget",
    "RiskGateSubagentProvenance",
    "RiskGateTaskArtifact",
    "RiskGateTaskDraft",
    "RiskGateTaskProposal",
    "RiskGateTrigger",
    "RiskGateTriggerDecision",
    "OptionSide",
    "OptionsDataSource",
    "OptionsSpec",
    "VolSurfacePoint",
    "VolSurfaceResult",
    "OptionsPositionLeg",
    "OptionsPosition",
    "GreeksSnapshot",
    "GreeksProfile",
    "OptionsStrategySpec",
    "OptionsBacktestReport",
    "SignalCandidate",
    "StrategySpec",
    "BacktestSummary",
    "StrategyReport",
    "StrategyVerdict",
]
